/**
 * Medical disclaimer constants for AI-assisted diagnosis
 * These must be included in all diagnosis/screening results returned to patients
 */
export const MEDICAL_DISCLAIMER = {
  vi:
    'Kết quả sàng lọc này chỉ mang tính chất tham khảo và không thay thế cho chẩn đoán y khoa chính thức. ' +
    'Kết quả được hỗ trợ bởi trí tuệ nhân tạo (AI) và đã được bác sĩ chuyên khoa xác nhận. ' +
    'Vui lòng tham khảo ý kiến bác sĩ chuyên khoa để được tư vấn chi tiết và điều trị phù hợp.',
  en:
    'This screening result is for reference only and does not replace official medical diagnosis. ' +
    'The result is AI-assisted and has been reviewed by a specialist physician. ' +
    'Please consult a specialist for detailed advice and appropriate treatment.',
};

export const AI_ANALYSIS_DISCLAIMER = {
  vi: 'Kết quả phân tích này được tạo bởi hệ thống AI và cần được bác sĩ chuyên khoa xác nhận trước khi sử dụng làm cơ sở chẩn đoán.',
  en: 'This analysis result is generated by AI and must be confirmed by a specialist physician before being used as a diagnostic basis.',
};

export const DATA_PROCESSING_CONSENT_INFO = {
  vi: {
    title: 'Thông tin về xử lý dữ liệu y tế',
    description:
      'Dữ liệu y tế của bạn sẽ được xử lý bởi hệ thống AI để hỗ trợ sàng lọc bệnh phổi. ' +
      'Dữ liệu được mã hóa và bảo mật theo tiêu chuẩn y tế quốc tế. ' +
      'Bạn có quyền yêu cầu xóa dữ liệu bất cứ lúc nào.',
  },
  en: {
    title: 'Medical Data Processing Information',
    description:
      'Your medical data will be processed by AI to assist in lung disease screening. ' +
      'Data is encrypted and secured according to international healthcare standards. ' +
      'You have the right to request data deletion at any time.',
  },
};
