export enum CountryEnum {
  VIET_NAM = '0',
  ANDORRA = '105',
  A_RAP_SAUDI = '110',
  AFGHANISTAN = '101',
  ALGERIE = '104',
  ANTIGUA_VA_BARBUDA = '108',
  ANGOLA = '106',
  ARGENTINA = '111',
  AO = '109',
  ARMENIA = '112',
  AZERBAIJAN = '113',
  BA_LAN = '118',
  BAHAMAS = '116',
  BAHRAIN = '117',
  AI_CAP = '102',
  ALBANIA = '103',
  BANGLADESH = '119',
  BELIZE = '122',
  BHUTAN = '124',
  BENIN = '123',
  BI = '125',
  BO_BIEN_NGA = '130',
  BO_DAO_NHA = '129',
  BOLIVIA = '126',
  BOSNA_VA_HERCEGOVINA = '127',
  BOTSWANA = '128',
  BRASIL = '131',
  BRUNEI = '132',
  BARBADOS = '120',
  BURKINA_FASO = '134',
  BURUNDI = '135',
  CABO_VERDE = '136',
  CAMEROON = '138',
  CAMPUCHIA = '139',
  BELARUS = '121',
  CHILE = '141',
  CANADA = '140',
  COLOMBIA = '142',
  COMOROS = '143',
  CONG_HOA_AN_DO = '115',
  CONG_HOA_AZERBAIJAN = '114',
  CONG_HOA_CROATIA = '148',
  CONG_HOA_DAN_CHU_CONGO = '145',
  CONG_HOA_CONGO = '144',
  CONG_HOA_DOMINICANA = '152',
  COSTA_RICA = '146',
  BULGARIA = '133',
  CROATIA = '147',
  DAN_MACH = '153',
  DJIBOUTI = '150',
  DOMINICA = '151',
  DUC = '155',
  CAC_TIEU_VUONG_QUOC_A_RAP_THONG_NHAT = '137',
  ECUADOR = '156',
  EL_SALVADOR = '157',
  ETHIOPIA = '160',
  ESTONIA = '159',
  ERITREA = '158',
  FIJI = '161',
  GHANA = '164',
  GAMBIA = '163',
  GABON = '162',
  GUATEMALA = '167',
  GRENADA = '165',
  GRUZIA = '166',
  GUINEA = '170',
  GUINEA_XICH_DAO = '169',
  GUINEA_BISSAU = '168',
  HA_LAN = '173',
  GUYANA = '171',
  HAN_QUOC = '174',
  HAITI = '172',
  CUBA = '149',
  HOA_KY = '175',
  DONG_TIMOR = '154',
  ICELAND = '179',
  HY_LAP = '178',
  INDONESIA = '180',
  IRAN = '181',
  IRAQ = '182',
  IRELAND = '183',
  ISRAEL = '184',
  JAMAICA = '185',
  JORDAN = '186',
  KAZAKHSTAN = '187',
  KENYA = '188',
  KIRIBATI = '189',
  KUWAIT = '190',
  KYRGYZSTAN = '192',
  LAO = '193',
  LATVIA = '194',
  HUNGARY = '177',
  LESOTHO = '195',
  LI_BAN = '196',
  LIBERIA = '197',
  LIBYA = '198',
  LIECHTENSTEIN = '199',
  LITVA = '200',
  HONDURAS = '176',
  LUXEMBOURG = '201',
  MACEDONIA = '202',
  MADAGASCAR = '203',
  MALAWI = '204',
  MALAYSIA = '205',
  MALDIVES = '206',
  MALI = '207',
  MALTA = '208',
  MAROC = '209',
  MAURITANIE = '211',
  MAURITIUS = '212',
  MEXICO = '213',
  MICRONESIA = '214',
  MOLDOVA = '215',
  MONACO = '216',
  MONG_CO = '217',
  MONTENEGRO = '218',
  MOZAMBIQUE = '219',
  MYANMA = '220',
  NA_UY = '225',
  NAM_PHI = '223',
  NAM_SUDAN = '222',
  NAMIBIA = '221',
  NAURU = '224',
  NEPAL = '226',
  NEW_ZEALAND = '227',
  NGA = '231',
  NHAT_BAN = '232',
  NICARAGUA = '228',
  NIGER = '229',
  NIGERIA = '230',
  OMAN = '233',
  PAKISTAN = '234',
  PALAU = '235',
  PANAMA = '236',
  PAPUA_NEW_GUINEA = '237',
  PARAGUAY = '238',
  PERU = '239',
  PHAN_LAN = '241',
  PHAP = '240',
  PHILIPPINES = '242',
  QATAR = '243',
  QUAN_DAO_MARSHALL = '210',
  ROMANIA = '244',
  RWANDA = '245',
  SAINT_KITTS_VA_NEVIS = '246',
  SAINT_LUCIA = '247',
  SAINT_VINCENT_VA_GRENADINES = '248',
  SAMOA = '249',
  SAN_MARINO = '250',
  SAO_TOME_VA_PRINCIPE = '251',
  SEC = '252',
  SENEGAL = '253',
  SERBIA = '254',
  SEYCHELLES = '255',
  SIERRA_LEONE = '256',
  SINGAPORE = '257',
  SIP = '191',
  SLOVAKIA = '258',
  SLOVENIA = '259',
  SOLOMON = '260',
  SOMALIA = '261',
  SRI_LANKA = '262',
  SUDAN = '263',
  SURINAME = '264',
  SWAZILAND = '265',
  SYRIA = '266',
  TAJIKISTAN = '267',
  TANZANIA = '268',
  TAY_BAN_NHA = '269',
  TCHAD = '270',
  THAI_LAN = '271',
  THANH_VATICAN = '290',
  THO_NHI_KY = '272',
  THUY_DIEN = '273',
  THUY_SI = '274',
  TOGO = '275',
  TONGA = '276',
  TRIEU_TIEN = '277',
  TRINIDAD_VA_TOBAGO = '278',
  TRUNG_PHI = '280',
  TRUNG_QUOC = '279',
  TUNISIA = '281',
  TURKMENISTAN = '282',
  TUVALU = '283',
  UC = '284',
  UGANDA = '285',
  UKRAINA = '286',
  URUGUAY = '287',
  UZBEKISTAN = '288',
  VANUATU = '289',
  VENEZUELA = '291',
  VUONG_QUOC_ANH = '107',
  Y = '292',
  YEMEN = '293',
  ZAMBIA = '294',
  ZIMBABWE = '295',
}

export const CountryName = {
  [CountryEnum.VIET_NAM]: 'Việt Nam',
  [CountryEnum.ANDORRA]: 'Andorra (An-đô-ra)',
  [CountryEnum.A_RAP_SAUDI]: 'Ả Rập Saudi (Ả Rập Xê-út)',
  [CountryEnum.AFGHANISTAN]: 'Afghanistan',
  [CountryEnum.ALGERIE]: 'Algérie (An-giê-ri)',
  [CountryEnum.ANTIGUA_VA_BARBUDA]:
    'Antigua và Barbuda (An-ti-goa và Bác-bu-da)',
  [CountryEnum.ANGOLA]: 'Angola (Ăng-gô-la)',
  [CountryEnum.ARGENTINA]: 'Argentina',
  [CountryEnum.AO]: 'Áo',
  [CountryEnum.ARMENIA]: 'Armenia (Ác-mê-ni-a)',
  [CountryEnum.AZERBAIJAN]: 'Azerbaijan (A-giéc-bai-gian)',
  [CountryEnum.BA_LAN]: 'Ba Lan',
  [CountryEnum.BAHAMAS]: 'Bahamas (Ba-ha-mát)',
  [CountryEnum.BAHRAIN]: 'Bahrain (Ba-ranh)',
  [CountryEnum.AI_CAP]: 'Ai Cập',
  [CountryEnum.ALBANIA]: 'Albania',
  [CountryEnum.BANGLADESH]: 'Bangladesh (Băng-la-đét)',
  [CountryEnum.BELIZE]: 'Belize (Bê-li-xê)',
  [CountryEnum.BHUTAN]: 'Bhutan (Bu-tan)',
  [CountryEnum.BENIN]: 'Benin (Bê-nanh)',
  [CountryEnum.BI]: 'Bỉ',
  [CountryEnum.BO_BIEN_NGA]: 'Bờ Biển Ngà (Cốt-đi-voa)',
  [CountryEnum.BO_DAO_NHA]: 'Bồ Đào Nha',
  [CountryEnum.BOLIVIA]: 'Bolivia (Bô-li-vi-a)',
  [CountryEnum.BOSNA_VA_HERCEGOVINA]:
    'Bosna và Hercegovina (Bốt-xni-a và Héc-dê-gô-vi-na)',
  [CountryEnum.BOTSWANA]: 'Botswana',
  [CountryEnum.BRASIL]: 'Brasil (Bra-xin)',
  [CountryEnum.BRUNEI]: 'Brunei (Bru-nây)',
  [CountryEnum.BARBADOS]: 'Barbados (Bác-ba-đốt)',
  [CountryEnum.BURKINA_FASO]: 'Burkina Faso (Buốc-ki-na Pha-xô)',
  [CountryEnum.BURUNDI]: 'Burundi',
  [CountryEnum.CABO_VERDE]: 'Cabo Verde (Cáp Ve)',
  [CountryEnum.CAMEROON]: 'Cameroon (Ca-mơ-run)',
  [CountryEnum.CAMPUCHIA]: 'Campuchia',
  [CountryEnum.BELARUS]: 'Belarus (Bê-la-rút)',
  [CountryEnum.CHILE]: 'Chile (Chi-lê)',
  [CountryEnum.CANADA]: 'Canada (Ca-na-đa; Gia Nã Đại)',
  [CountryEnum.COLOMBIA]: 'Colombia (Cô-lôm-bi-a)',
  [CountryEnum.COMOROS]: 'Comoros (Cô-mo)',
  [CountryEnum.CONG_HOA_AN_DO]: 'Cộng hòa Ấn Độ',
  [CountryEnum.CONG_HOA_AZERBAIJAN]: 'Cộng hòa Azerbaijan',
  [CountryEnum.CONG_HOA_CROATIA]: 'Cộng hòa Croatia',
  [CountryEnum.CONG_HOA_DAN_CHU_CONGO]:
    'Cộng hòa Dân chủ Congo (Congo-Kinshasa)',
  [CountryEnum.CONG_HOA_CONGO]: 'Cộng hòa Congo (Công-gô; Congo-Brazzaville)',
  [CountryEnum.CONG_HOA_DOMINICANA]: 'Cộng hòa Dominicana (Đô-mi-ni-ca-na)',
  [CountryEnum.COSTA_RICA]: 'Costa Rica (Cốt-xta Ri-ca)',
  [CountryEnum.BULGARIA]: 'Bulgaria (Bungari)',
  [CountryEnum.CROATIA]: 'Croatia (Crô-a-ti-a)',
  [CountryEnum.DAN_MACH]: 'Đan Mạch',
  [CountryEnum.DJIBOUTI]: 'Djibouti (Gi-bu-ti)',
  [CountryEnum.DOMINICA]: 'Dominica (Đô-mi-ni-ca)',
  [CountryEnum.DUC]: 'Đức',
  [CountryEnum.CAC_TIEU_VUONG_QUOC_A_RAP_THONG_NHAT]:
    'Các Tiểu Vương quốc Ả Rập Thống nhất',
  [CountryEnum.ECUADOR]: 'Ecuador (Ê-cu-a-đo)',
  [CountryEnum.EL_SALVADOR]: 'El Salvador (En Xan-va-đo)',
  [CountryEnum.ETHIOPIA]: 'Ethiopia (Ê-t(h)i-ô-pi-a)',
  [CountryEnum.ESTONIA]: 'Estonia (E-xtô-ni-a)',
  [CountryEnum.ERITREA]: 'Eritrea (Ê-ri-tơ-ri-a)',
  [CountryEnum.FIJI]: 'Fiji (Phi-gi)',
  [CountryEnum.GHANA]: 'Ghana (Ga-na)',
  [CountryEnum.GAMBIA]: 'Gambia (Găm-bi-a)',
  [CountryEnum.GABON]: 'Gabon (Ga-bông)',
  [CountryEnum.GUATEMALA]: 'Guatemala (Goa-tê-ma-la)',
  [CountryEnum.GRENADA]: 'Grenada (Grê-na-đa)',
  [CountryEnum.GRUZIA]: 'Gruzia (Gru-di-a)',
  [CountryEnum.GUINEA]: 'Guinea (Ghi-nê)',
  [CountryEnum.GUINEA_XICH_DAO]: 'Guinea Xích Đạo (Ghi-nê Xích Đạo)',
  [CountryEnum.GUINEA_BISSAU]: 'Guinea-Bissau (Ghi-nê Bít-xao)',
  [CountryEnum.HA_LAN]: 'Hà Lan (Hòa Lan)',
  [CountryEnum.GUYANA]: 'Guyana (Gai-a-na)',
  [CountryEnum.HAN_QUOC]: 'Hàn Quốc (Nam Hàn)',
  [CountryEnum.HAITI]: 'Haiti (Ha-i-ti)',
  [CountryEnum.CUBA]: 'Cuba (Cu-ba)',
  [CountryEnum.HOA_KY]: 'Hoa Kỳ (Mỹ)',
  [CountryEnum.DONG_TIMOR]: 'Đông Timor (Ti-mo Lex-te)',
  [CountryEnum.ICELAND]: 'Iceland (Ai xơ len)',
  [CountryEnum.HY_LAP]: 'Hy Lạp',
  [CountryEnum.INDONESIA]: 'Indonesia (In-đô-nê-xi-a)',
  [CountryEnum.IRAN]: 'Iran',
  [CountryEnum.IRAQ]: 'Iraq (I-rắc)',
  [CountryEnum.IRELAND]: 'Ireland (Ai-len)',
  [CountryEnum.ISRAEL]: 'Israel (I-xra-en)',
  [CountryEnum.JAMAICA]: 'Jamaica (Gia-mai-ca)',
  [CountryEnum.JORDAN]: 'Jordan (Gioóc-đan-ni)',
  [CountryEnum.KAZAKHSTAN]: 'Kazakhstan (Ca-dắc-xtan)',
  [CountryEnum.KENYA]: 'Kenya (Kê-nhi-a)',
  [CountryEnum.KIRIBATI]: 'Kiribati',
  [CountryEnum.KUWAIT]: 'Kuwait (Cô-oét)',
  [CountryEnum.KYRGYZSTAN]: 'Kyrgyzstan (Cư-rơ-gư-xtan)',
  [CountryEnum.LAO]: 'Lào',
  [CountryEnum.LATVIA]: 'Latvia (Lat-vi-a)',
  [CountryEnum.HUNGARY]: 'Hungary (Hung-ga-ri)',
  [CountryEnum.LESOTHO]: 'Lesotho (Lê-xô-thô)',
  [CountryEnum.LI_BAN]: 'Li ban (Li-băng)',
  [CountryEnum.LIBERIA]: 'Liberia (Li-bê-ri-a)',
  [CountryEnum.LIBYA]: 'Libya (Li-bi)',
  [CountryEnum.LIECHTENSTEIN]: 'Liechtenstein (Lích-ten-xtai)',
  [CountryEnum.LITVA]: 'Litva (Lít-va)',
  [CountryEnum.HONDURAS]: 'Honduras (Hôn-đu-rát) (Ôn-đu-rát)',
  [CountryEnum.LUXEMBOURG]: 'Luxembourg (Lúc-xem-bua)',
  [CountryEnum.MACEDONIA]: 'Macedonia (Mã Cơ Đốn) (Ma-xê-đô-ni-a)',
  [CountryEnum.MADAGASCAR]: 'Madagascar',
  [CountryEnum.MALAWI]: 'Malawi (Ma-la-uy)',
  [CountryEnum.MALAYSIA]: 'Malaysia (Mã Lai Tây Á) (Ma-lay-xi-a)',
  [CountryEnum.MALDIVES]: 'Maldives (Man-di-vơ)',
  [CountryEnum.MALI]: 'Mali',
  [CountryEnum.MALTA]: 'Malta (Man-ta)',
  [CountryEnum.MAROC]: 'Maroc',
  [CountryEnum.MAURITANIE]: 'Mauritanie (Mô-ri-ta-ni)',
  [CountryEnum.MAURITIUS]: 'Mauritius (Mô-ri-xơ)',
  [CountryEnum.MEXICO]: 'Mexico (Mê-hi-cô)',
  [CountryEnum.MICRONESIA]: 'Micronesia (Mi-crô-nê-di)',
  [CountryEnum.MOLDOVA]: 'Moldova (Môn-đô-va)',
  [CountryEnum.MONACO]: 'Monaco (Mô-na-cô)',
  [CountryEnum.MONG_CO]: 'Mông Cổ',
  [CountryEnum.MONTENEGRO]: 'Montenegro (Môn-tê-nê-grô)',
  [CountryEnum.MOZAMBIQUE]: 'Mozambique (Mô-dăm-bích)',
  [CountryEnum.MYANMA]: 'Myanma (Mi-an-ma)',
  [CountryEnum.NA_UY]: 'Na Uy',
  [CountryEnum.NAM_PHI]: 'Nam Phi',
  [CountryEnum.NAM_SUDAN]: 'Nam Sudan',
  [CountryEnum.NAMIBIA]: 'Namibia (Na-mi-bi-a)',
  [CountryEnum.NAURU]: 'Nauru (Nau-ru)',
  [CountryEnum.NEPAL]: 'Nepal (Nê-pan)',
  [CountryEnum.NEW_ZEALAND]: 'New Zealand (Niu Di-lân) (Tân Tây Lan)',
  [CountryEnum.NGA]: 'Nga',
  [CountryEnum.NHAT_BAN]: 'Nhật Bản',
  [CountryEnum.NICARAGUA]: 'Nicaragua (Ni-ca-ra-goa)',
  [CountryEnum.NIGER]: 'Niger (Ni-giê)',
  [CountryEnum.NIGERIA]: 'Nigeria (Ni-giê-ri-a)',
  [CountryEnum.OMAN]: 'Oman (Ô-man)',
  [CountryEnum.PAKISTAN]: 'Pakistan (Pa-kít-xtan)',
  [CountryEnum.PALAU]: 'Palau (Pa-lau)',
  [CountryEnum.PANAMA]: 'Panama (Pa-na-ma)',
  [CountryEnum.PAPUA_NEW_GUINEA]: 'Papua New Guinea (Pa-pua Niu Ghi-nê)',
  [CountryEnum.PARAGUAY]: 'Paraguay (Pa-ra-goay)',
  [CountryEnum.PERU]: 'Peru (Pê-ru)',
  [CountryEnum.PHAN_LAN]: 'Phần Lan',
  [CountryEnum.PHAP]: 'Pháp (Pháp Lan Tây)',
  [CountryEnum.PHILIPPINES]: 'Philippines (Phi-líp-pin)',
  [CountryEnum.QATAR]: 'Qatar (Ca-ta)',
  [CountryEnum.QUAN_DAO_MARSHALL]: 'Quần đảo Marshall',
  [CountryEnum.ROMANIA]: 'Romania (Ru-ma-ni, Lỗ Ma Ni)',
  [CountryEnum.RWANDA]: 'Rwanda (Ru-an-đa)',
  [CountryEnum.SAINT_KITTS_VA_NEVIS]:
    'Saint Kitts và Nevis (Xanh Kít và Nê-vít)',
  [CountryEnum.SAINT_LUCIA]: 'Saint Lucia (San-ta Lu-xi-a)',
  [CountryEnum.SAINT_VINCENT_VA_GRENADINES]:
    'Saint Vincent và Grenadines (Xanh Vin-xen và Grê-na-din)',
  [CountryEnum.SAMOA]: 'Samoa (Xa-moa)',
  [CountryEnum.SAN_MARINO]: 'San Marino (San Ma-ri-nô)',
  [CountryEnum.SAO_TOME_VA_PRINCIPE]:
    'São Tomé và Príncipe (Sao Tô-mê và Prin-xi-pê)',
  [CountryEnum.SEC]: 'Séc (Tiệp)',
  [CountryEnum.SENEGAL]: 'Sénégal (Xê-nê-gan)',
  [CountryEnum.SERBIA]: 'Serbia (Xéc-bi-a)',
  [CountryEnum.SEYCHELLES]: 'Seychelles (Xây-sen)',
  [CountryEnum.SIERRA_LEONE]: 'Sierra Leone (Xi-ê-ra Lê-ôn)',
  [CountryEnum.SINGAPORE]: 'Singapore (Xinh-ga-po)',
  [CountryEnum.SIP]: 'Síp',
  [CountryEnum.SLOVAKIA]: 'Slovakia (Xlô-va-ki-a)',
  [CountryEnum.SLOVENIA]: 'Slovenia (Xlô-ven-ni-a)',
  [CountryEnum.SOLOMON]: 'Solomon (Xô-lô-môn)',
  [CountryEnum.SOMALIA]: 'Somalia (Xô-ma-li)',
  [CountryEnum.SRI_LANKA]: 'Sri Lanka (Xri Lan-ca)',
  [CountryEnum.SUDAN]: 'Sudan (Xu-đăng)',
  [CountryEnum.SURINAME]: 'Suriname (Xu-ri-nam)',
  [CountryEnum.SWAZILAND]: 'Swaziland (Xoa-di-len)',
  [CountryEnum.SYRIA]: 'Syria (Xi-ri)',
  [CountryEnum.TAJIKISTAN]: 'Tajikistan (Tát-gi-kít-xtan)',
  [CountryEnum.TANZANIA]: 'Tanzania (Tan-da-ni-a)',
  [CountryEnum.TAY_BAN_NHA]: 'Tây Ban Nha',
  [CountryEnum.TCHAD]: 'Tchad (Sát)',
  [CountryEnum.THAI_LAN]: 'Thái Lan',
  [CountryEnum.THANH_VATICAN]: 'Thành Vatican (Va-ti-căng)/Tòa Thánh',
  [CountryEnum.THO_NHI_KY]: 'Thổ Nhĩ Kỳ',
  [CountryEnum.THUY_DIEN]: 'Thụy Điển',
  [CountryEnum.THUY_SI]: 'Thụy Sĩ (Thụy Sỹ)',
  [CountryEnum.TOGO]: 'Togo (Tô-gô)',
  [CountryEnum.TONGA]: 'Tonga (Tông-ga)',
  [CountryEnum.TRIEU_TIEN]: 'Triều Tiên',
  [CountryEnum.TRINIDAD_VA_TOBAGO]:
    'Trinidad và Tobago (Tri-ni-đát và Tô-ba-gô)',
  [CountryEnum.TRUNG_PHI]: 'Trung Phi',
  [CountryEnum.TRUNG_QUOC]: 'Trung Quốc',
  [CountryEnum.TUNISIA]: 'Tunisia (Tuy-ni-di)',
  [CountryEnum.TURKMENISTAN]: 'Turkmenistan (Tuốc-mê-ni-xtan)',
  [CountryEnum.TUVALU]: 'Tuvalu',
  [CountryEnum.UC]: 'Úc (Ốt-xrây-li-a)',
  [CountryEnum.UGANDA]: 'Uganda (U-gan-đa)',
  [CountryEnum.UKRAINA]: 'Ukraina (U-crai-na)',
  [CountryEnum.URUGUAY]: 'Uruguay (U-ru-goay)',
  [CountryEnum.UZBEKISTAN]: 'Uzbekistan (U-dơ-bê-kít-xtan)',
  [CountryEnum.VANUATU]: 'Vanuatu (Va-nu-a-tu)',
  [CountryEnum.VENEZUELA]: 'Venezuela (Vê-nê-xu(y)-ê-la)',
  [CountryEnum.VUONG_QUOC_ANH]: 'Vương quốc Liên hiệp Anh và Bắc Ireland',
  [CountryEnum.Y]: 'Ý (I-ta-li-a)',
  [CountryEnum.YEMEN]: 'Yemen (Y-ê-men)',
  [CountryEnum.ZAMBIA]: 'Zambia (Dăm-bi-a)',
  [CountryEnum.ZIMBABWE]: 'Zimbabwe (Dim-ba-bu-ê)',
};
