export enum DoctorTitle {
  PROFESSOR_PHD_DOCTOR = 'Giáo sư, Tiến sĩ, Bác sĩ',
  ASSOCIATE_PROFESSOR_PHD_DOCTOR = 'Phó giáo sư, Tiến sĩ, Bác sĩ',
  PHD_DOCTOR = 'Tiến sĩ, Bác sĩ',
  MASTER_DOCTOR = 'Thạc sĩ, Bác sĩ',
  SPECIALIST_DOCTOR_2 = 'Bác sĩ chuyên khoa 2',
  SPECIALIST_DOCTOR_1 = 'Bác sĩ chuyên khoa 1',
  MASTER_SPECIALIST_DOCTOR_1 = 'Thạc sĩ, Bác sĩ chuyên khoa 1',
  MASTER_SPECIALIST_DOCTOR_2 = 'Thạc sĩ, Bác sĩ chuyên khoa 2',
  PHD_SPECIALIST_DOCTOR_2 = 'Tiến sĩ, Bác sĩ chuyên khoa 2',
  DOCTOR = 'Bác sĩ',
  MASTER_PHARMACIST = 'Thạc sĩ, Dược sĩ',
  PHARMACIST = 'Dược sĩ',
  PHD_PHARMACIST = 'Tiến sĩ, Dược sĩ',
  SPECIALIST_PHARMACIST_1 = 'Dược sĩ chuyên khoa 1',
  ASSOCIATE_PROFESSOR_PHD_PHARMACIST = 'Phó giáo sư, Tiến sĩ, Dược sĩ',
  PROFESSOR_PHD_PHARMACIST = 'Giáo sư, Tiến sĩ, Dược sĩ',
  SPECIALIST_PHARMACIST_2 = 'Dược sĩ chuyên khoa 2',
}
