export enum EthnicityEnum {
  KINH = '1',
  TAY = '2',
  THAI = '3',
  HOA = '4',
  KHO_ME = '5',
  MUONG = '6',
  NUNG = '7',
  HMONG = '8',
  DAO = '9',
  GIA_RAI = '10',
  NGAI = '11',
  EDE = '12',
  BA_NA = '13',
  XO_DANG = '14',
  SAN_CHAY = '15',
  CO_HO = '16',
  CHAM = '17',
  SAN_DIU = '18',
  HRE = '19',
  MNONG = '20',
  RA_GLAI = '21',
  XTIENG = '22',
  BRU_VAN_KIEU = '23',
  THO = '24',
  GIAY = '25',
  CO_TU = '26',
  GIE_TRIENG = '27',
  MA = '28',
  KHO_MU = '29',
  CO = '30',
  TA_OI = '31',
  CHO_RO = '32',
  KHANG = '33',
  XINH_MUN = '34',
  HA_NHI = '35',
  CHU_RU = '36',
  LAO = '37',
  LA_CHI = '38',
  LA_HA = '39',
  PHU_LA = '40',
  LA_HU = '41',
  LU = '42',
  LO_LO = '43',
  CHUT = '44',
  MANG = '45',
  PA_THEN = '46',
  CO_LAO = '47',
  CONG = '48',
  BO_Y = '49',
  SI_LA = '50',
  PU_PEO = '51',
  BRAU = '52',
  O_DU = '53',
  RO_MAM = '54',
  FOREIGNER = '55',
  UNKNOWN = '56',
}

export const EthnicityName = {
  [EthnicityEnum.KINH]: 'Kinh',
  [EthnicityEnum.TAY]: 'Tày',
  [EthnicityEnum.THAI]: 'Thái',
  [EthnicityEnum.HOA]: 'Hoa',
  [EthnicityEnum.KHO_ME]: 'Khơ-me',
  [EthnicityEnum.MUONG]: 'Mường',
  [EthnicityEnum.NUNG]: 'Nùng',
  [EthnicityEnum.HMONG]: 'HMông',
  [EthnicityEnum.DAO]: 'Dao',
  [EthnicityEnum.GIA_RAI]: 'Gia-rai',
  [EthnicityEnum.NGAI]: 'Ngái',
  [EthnicityEnum.EDE]: 'Ê-đê',
  [EthnicityEnum.BA_NA]: 'Ba na',
  [EthnicityEnum.XO_DANG]: 'Xơ-Đăng',
  [EthnicityEnum.SAN_CHAY]: 'Sán Chay',
  [EthnicityEnum.CO_HO]: 'Cơ-ho',
  [EthnicityEnum.CHAM]: 'Chăm',
  [EthnicityEnum.SAN_DIU]: 'Sán Dìu',
  [EthnicityEnum.HRE]: 'Hrê',
  [EthnicityEnum.MNONG]: 'Mnông',
  [EthnicityEnum.RA_GLAI]: 'Ra-glai',
  [EthnicityEnum.XTIENG]: 'Xtiêng',
  [EthnicityEnum.BRU_VAN_KIEU]: 'Bru-Vân Kiều',
  [EthnicityEnum.THO]: 'Thổ',
  [EthnicityEnum.GIAY]: 'Giáy',
  [EthnicityEnum.CO_TU]: 'Cơ-tu',
  [EthnicityEnum.GIE_TRIENG]: 'Gié Triêng',
  [EthnicityEnum.MA]: 'Mạ',
  [EthnicityEnum.KHO_MU]: 'Khơ-mú',
  [EthnicityEnum.CO]: 'Co',
  [EthnicityEnum.TA_OI]: 'Tà-ôi',
  [EthnicityEnum.CHO_RO]: 'Chơ-ro',
  [EthnicityEnum.KHANG]: 'Kháng',
  [EthnicityEnum.XINH_MUN]: 'Xinh-mun',
  [EthnicityEnum.HA_NHI]: 'Hà Nhì',
  [EthnicityEnum.CHU_RU]: 'Chu ru',
  [EthnicityEnum.LAO]: 'Lào',
  [EthnicityEnum.LA_CHI]: 'La Chí',
  [EthnicityEnum.LA_HA]: 'La Ha',
  [EthnicityEnum.PHU_LA]: 'Phù Lá',
  [EthnicityEnum.LA_HU]: 'La Hủ',
  [EthnicityEnum.LU]: 'Lự',
  [EthnicityEnum.LO_LO]: 'Lô Lô',
  [EthnicityEnum.CHUT]: 'Chứt',
  [EthnicityEnum.MANG]: 'Mảng',
  [EthnicityEnum.PA_THEN]: 'Pà Thẻn',
  [EthnicityEnum.CO_LAO]: 'Co Lao',
  [EthnicityEnum.CONG]: 'Cống',
  [EthnicityEnum.BO_Y]: 'Bố Y',
  [EthnicityEnum.SI_LA]: 'Si La',
  [EthnicityEnum.PU_PEO]: 'Pu Péo',
  [EthnicityEnum.BRAU]: 'Brâu',
  [EthnicityEnum.O_DU]: 'Ơ Đu',
  [EthnicityEnum.RO_MAM]: 'Rơ măm',
  [EthnicityEnum.FOREIGNER]: 'Người nước ngoài',
  [EthnicityEnum.UNKNOWN]: 'Không rõ',
};
