export enum AuditAction {
  CREATE_RECORD = 'CREATE_RECORD',
  UPDATE_RECORD = 'UPDATE_RECORD',
  LINK_RECORD = 'LINK_RECORD',
  COMPLETE_RECORD = 'COMPLETE_RECORD',
  REOPEN_RECORD = 'REOPEN_RECORD',
  SIGN_RECORD = 'SIGN_RECORD',
  CREATE_PRESCRIPTION = 'CREATE_PRESCRIPTION',
  UPDATE_PRESCRIPTION = 'UPDATE_PRESCRIPTION',
  CANCEL_PRESCRIPTION = 'CANCEL_PRESCRIPTION',
}
